// Урок от Java Blogger 007

package ru.site.zzz.guilessons;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author pgapr
 */
public class Lesson4 extends javax.swing.JFrame {

    /**
     * Creates new form Lesson4
     */
    public Lesson4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        breadWhite = new javax.swing.JRadioButton();
        breadGray = new javax.swing.JRadioButton();
        breadDarnitsky = new javax.swing.JRadioButton();
        findOutThePrice = new javax.swing.JButton();
        price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setText("Хлебный магазин");

        breadWhite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        breadWhite.setText("Белый");
        breadWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadWhiteActionPerformed(evt);
            }
        });

        breadGray.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        breadGray.setText("Серый");
        breadGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadGrayActionPerformed(evt);
            }
        });

        breadDarnitsky.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        breadDarnitsky.setText("Дарницкий");
        breadDarnitsky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadDarnitskyActionPerformed(evt);
            }
        });

        findOutThePrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        findOutThePrice.setText("Узнать цену");
        findOutThePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findOutThePriceActionPerformed(evt);
            }
        });

        price.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(breadDarnitsky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breadGray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breadWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findOutThePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Name)
                .addGap(18, 18, 18)
                .addComponent(breadWhite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breadGray)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breadDarnitsky)
                .addGap(18, 18, 18)
                .addComponent(findOutThePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void breadGrayActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    if (breadGray.isSelected()) {
            breadWhite.setSelected(false);
            breadDarnitsky.setSelected(false);
    }
    }                                         

    private void findOutThePriceActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        if (breadWhite.isSelected()) {
            int total = 20;
            price.setText(String.valueOf(total + " руб."));
        } else if (breadGray.isSelected()) {
            int total = 25;
            price.setText(String.valueOf(total + " руб."));
        } else if (breadDarnitsky.isSelected()) {
            int total = 32;
            price.setText(String.valueOf(total + " руб."));
    }
//                
//                
//                
    }                                               

    private void breadWhiteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if (breadWhite.isSelected()) {
            breadGray.setSelected(false);
            breadDarnitsky.setSelected(false);
        }
    }                                          

    private void breadDarnitskyActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        if (breadDarnitsky.isSelected()) {
            breadWhite.setSelected(false);
            breadGray.setSelected(false);
        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lesson4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Name;
    private javax.swing.JRadioButton breadDarnitsky;
    private javax.swing.JRadioButton breadGray;
    private javax.swing.JRadioButton breadWhite;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton findOutThePrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price;
    // End of variables declaration                   
}
